# remote_theme: just-the-docs/just-the-docs
theme: just-the-docs

incremental: true

jdk_distribution: "21.0.6-librca"

exclude: 
  - lab_SAVE
  - lectures_SAVE
  - hwk_SAVE

course: "CMPSC 156"
title: "CS156 f25"
quarter: "Fall 2025"
QXX: F25
qxx: f25
baseurl: "/f25"
slack_help_lecture_discussion: TBD
sample_team: f25-04

ta_list_full: Sanjay Chandrasekaran, Kate Larrick
la_list_full: Daniel Jensen, Derek Kirschbaum, Samuel Zhu, Divyani Punj
discussion_section_day: Wednesday
discussion_section_times: 4pm, 6pm

help_windows_link: https://ucsb-cs156-f25.slack.com/archives/C09A5LE7T89
help_macos_link: https://ucsb-cs156-f25.slack.com/archives/C09A5LGBP25
help_lecture_discussion: https://ucsb-cs156-f25.slack.com/archives/C099W8E5W5S

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Aux links for the upper right navigation
aux_links:
  "CS156 main website":
    - "https://ucsb-cs156.github.io/"
  "github":
    - "//github.com/ucsb-cs156-f25"
  "Canvas":
    - "https://ucsb.instructure.com/courses/27687"

# TODO: replace canvas link above with specific one
# such as https://www.canvas.ucsb.edu/courses/12345

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ucsb-cs156/f25" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately


# Collections for website data
collections:
  modules:
  staffers:
    permalink: "/:path/"
    output: true
  lectures:
    permalink: "/lectures/:path/"
    output: true
  hwk:
    permalink: "/hwk/:path/"
    output: true
# Default layouts for each collection type
defaults:
  - scope:
      type: lectures
    values:
      layout: default
  - scope:
      type: hwk
    values:
      layout: default
  - scope:
      path: ""
      type: staffers
    values:
      layout: staffer
      subpath: "/assets/images/"

teams: 
  - team: f25-01
    dokku: "01"
    team01_project: "3"
    team02_project: "20"
    legacy_project: "tbd"
    slack: https://ucsb-cs156-f25.slack.com/archives/C09GHFZBLF7
  - team: f25-02
    dokku: "02"
    team01_project: "4"
    team02_project: "22"
    legacy_project: "tbd"
    slack: https://ucsb-cs156-f25.slack.com/archives/C09GZ6G8YFK
  - team: f25-03
    dokku: "03"
    team01_project: "5"
    team02_project: "23"
    legacy_project: "tbd"
    slack: https://ucsb-cs156-f25.slack.com/archives/C09GKJMEMM4
  - team: f25-04
    dokku: "04"
    team01_project: "6"
    team02_project: "24"
    legacy_project: "tbd" 
    slack: https://ucsb-cs156-f25.slack.com/archives/C09GQV2B4UU
  - team: f25-05
    dokku: "05"
    team01_project: "7"
    team02_project: "25"
    legacy_project: "tbd"
    slack: https://ucsb-cs156-f25.slack.com/archives/C09GQV265V2
  - team: f25-06
    dokku: "06"
    team01_project: "8"
    team02_project: "26"
    legacy_project: "tbd" 
    slack: https://ucsb-cs156-f25.slack.com/archives/C09HDR951PA
  - team: f25-07
    dokku: "07"
    team01_project: "9"
    team02_project: "27"
    legacy_project: "tbd" 
    slack: https://ucsb-cs156-f25.slack.com/archives/C09GQV265V2
  - team: f25-08
    dokku: "08"
    team01_project: "10"
    team02_project: "28"
    legacy_project: "tbd" 
    slack: https://ucsb-cs156-f25.slack.com/archives/C09G5988CTH
  - team: f25-09
    dokku: "09"
    team01_project: "11"
    team02_project: "29"
    legacy_project: "tbd" 
    slack: https://ucsb-cs156-f25.slack.com/archives/C09GHFZ372R
  - team: f25-10
    dokku: "10"
    team01_project: "12"
    team02_project: "30"
    legacy_project: "tbd" 
    slack: https://ucsb-cs156-f25.slack.com/archives/C08L6M9TEBV
  - team: f25-11
    dokku: "11"
    team01_project: "13"
    team02_project: "31"
    legacy_project: "tbd" 
    slack: https://ucsb-cs156-f25.slack.com/archives/C08L26YQDQV
  - team: f25-12
    dokku: "12"
    team01_project: "14"
    team02_project: "33"
    legacy_project: "tbd" 
    slack: https://ucsb-cs156-f25.slack.com/archives/C09GQV2S6BW
  - team: f25-13
    dokku: "13"
    team01_project: "15"
    team02_project: "35"
    legacy_project: "tbd"
    slack: https://ucsb-cs156-f25.slack.com/archives/C09GHFYSZ2R
  - team: f25-14
    dokku: "14"
    team01_project: "16"
    team02_project: "36"
    legacy_project: "tbd" 
    slack: https://ucsb-cs156-f25.slack.com/archives/C09GKJN9WQ6
  - team: f25-15
    dokku: "15"
    team01_project: "17"
    team02_project: "38"
    legacy_project: "tbd"
    slack: https://ucsb-cs156-f25.slack.com/archives/C09HDR9E75E
  - team: f25-16
    dokku: "16"
    team01_project: "18"
    team02_project: "37"
    legacy_project: "tbd" 
    slack: https://ucsb-cs156-f25.slack.com/archives/C09GQV2UVGC


