# remote_theme: just-the-docs/just-the-docs
theme: just-the-docs

incremental: true

jdk_distribution: "21.0.6-librca"

course: "CMPSC 156"
title: "CS156 S25"
quarter: "Spring 2025"
QXX: S25
qxx: s25
baseurl: "/s25"
slack_help_lecture_discussion: TBD
sample_team: s25-04

ta_list_full: Sangita Kunapuli, Amey Walimbe
la_list_full: Daniel Jensen, Benjamin Conte, Samuel Zhu, Divyani Punj
discussion_section_day: Wednesday
discussion_section_times: 6pm, 7pm

help_windows_link: https://ucsb-cs156-s25.slack.com/archives/C08L76J189Y
help_macos_link: https://ucsb-cs156-s25.slack.com/archives/C08LFHL9P5F
help_lecture_discussion: https://ucsb-cs156-s25.slack.com/archives/C08KX29APQ8

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Aux links for the upper right navigation
aux_links:
  "CS156 main website":
    - "https://ucsb-cs156.github.io/"
  "github":
    - "//github.com/ucsb-cs156-s25"
  "Canvas":
    - "https://ucsb.instructure.com/courses/25659"

# TODO: replace canvas link above with specific one
# such as https://www.canvas.ucsb.edu/courses/12345

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ucsb-cs156/s25" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

help_macos_link: https://ucsb-cs156-s25.slack.com/
help_windows_link: https://ucsb-cs156-s25.slack.com/

# Collections for website data
collections:
  modules:
  staffers:
    permalink: "/:path/"
    output: true
  lectures:
    permalink: "/lectures/:path/"
    output: true
  hwk:
    permalink: "/hwk/:path/"
    output: true
# Default layouts for each collection type
defaults:
  - scope:
      type: lectures
    values:
      layout: default
  - scope:
      type: hwk
    values:
      layout: default
  - scope:
      path: ""
      type: staffers
    values:
      layout: staffer
      subpath: "/assets/images/"

teams: 
  - team: s25-01
    dokku: "01"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-02
    dokku: "02"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-03
    dokku: "03"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-04
    dokku: "04"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-05
    dokku: "05"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-06
    dokku: "06"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-07
    dokku: "07"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-08
    dokku: "08"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-09
    dokku: "09"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-10
    dokku: "10"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-11
    dokku: "11"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-12
    dokku: "12"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-13
    dokku: "13"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-14
    dokku: "14"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-15
    dokku: "15"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
  - team: s25-16
    dokku: "16"
    team02_project: tbd
    slack: https://ucsb-cs156-s25.slack.com/archives/tbd
